### PR TITLE
Add CORDEX support

### PR DESCRIPTION
**Pull request by ScottWales**
Add support for CORDEX datasets

Questions

 - [ ] Is this a good way to make the CLI more generic?
 - [ ] Use a JSON file for the controlled vocabulary instead of downloading from ESGF
 - [ ] Check all datasets findable (some may only be on dkrz?)

### CODE REVIEW

**Comment by paolap** [comment]
so you're basically suggesting to have a new click class for each project and that would define the different facets in there. The facets definition would also be made on the fly by retrieving them from the ESGF, or alternatively from a json file.
I guess I like the second option better (son) it is unlikely the facets will be updated very often if at all and we can always update the son files. This means the tool will still work when the ESGF node is offline.
I will check dkrz and generally cortex organisation asap but I'm bit busy today

**Comment by ScottWales** [comment]
It should be possible to have a common `Command` class, just using a different dictionary for each one.

Agree that using a json file would be better, getting the values from ESGF was just a quick solution to getting something working.

**Comment by paolap** [comment]
sounds good, if you're pushing this could you make sure you're fixing issue #93 should be trivial

**Comment by ScottWales** [comment]
No problem, I'll make a separate pull request with a #93 fix so we can merge that straight away

**Comment by paolap** [comment]
So I checked back online and the short answer for ESGF codes they're available on all nodes but only dkrz and a few others (not lcmdi or NCI ) have the cortex related facets available: “Domain”, “Driving Model”, “Downscaling Realisation”
These are important for users to be able to search without having to discover beforehand model names etc.
Details are in the related issue already.
I guess the fact that you could search for something means that we have already this data on MAS I suppose it's from publications, there's also some in al33.
There's more cortex data in ua8 the one that NCI hasn't yet decided where it should be located, ie.e the one that comes from non ESGF.
The simple thing would be to make sure this gets added to MAS and can be found by local search. Until then there's nothing we can do.
I will try to add the cortex attributes to the son file that local_search refers to as a first step to see if this can work as it is with what we have.

**Pull request closed without merging**
