### PR TITLE
Add missing esm experiments

### PR DESCRIPTION
**Pull request by lewisjared**
There were a number of esm experiments which were missing, but are valid CMIP6 experiments

### CODE REVIEW

**Comment by lewisjared** [comment]
@znicholls FYI

**Comment by znicholls** [comment]
It's surprising they're missing because those experiments are in `clef/data/CMIP6_experiment_id.json`

**Comment by paolap** [comment]
Hi,

those documents get updated, we did have an update in a different branch ready to be install as a new version. So I won't merge this, but we're waiting on NCI to give us the ok to use their new database which is also included, in theory they should give us an answer at any moment so updating to a new version right now is inconvenient. If we don't get any answer by tomorrow, I'll update only the json files and create a new intermediate version. Apologies for the inconvenience.

**Comment by paolap** [comment]
This is now fixed in analysis3-unstable
unfortunately we couldn't move the new database yet, hopefully next week, so for the moment ironically anything published by NCI isn't shown in the results i.e. all ACCESS models. This files though are always in /g/data/fs38

**Pull request closed without merging**
